services:     
  tunihire_backend:
    image: ${NEXUS_REGISTRY_URL}/tunihire-backend:${BASE_APP_VERSION}
    build:
      context: .
      dockerfile: back-end.dockerfile
    container_name: tunihire_backend_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - tunihire_db    
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://tunihire_db:27017/tunihire_prod
      # Using environment variables for secrets
      SESSION_SECRET: ${SESSION_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_APP_USER: ${EMAIL_APP_USER}
      EMAIL_APP_PASSWORD: ${EMAIL_APP_PASSWORD}
      # Fixed URLs
      GITHUB_CALLBACK_URL: "http://localhost:5000/auth/github/callback"
      FRONTEND_URL: "http://localhost:3000"
      SMTP_PORT: "587"
    networks:
      - tunihire_network

  tunihire_db:
    image: mongo:4.4
    container_name: tunihire_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db   
    networks:
      - tunihire_network
  tunihire_frontend:
    image: node:18-alpine
    container_name: tunihire_frontend_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - tunihire_backend
    volumes:
      - ./Front-End:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"    
    environment:      
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: "http://localhost:5000"
    networks:
      - tunihire_network
  tunihire_company_panel:
    image: node:18-alpine
    container_name: tunihire_company_panel_app
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - tunihire_backend
    volumes:
      - ./Company-Panel:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"    
    environment:
      NODE_ENV: development
      PORT: 3001
      NEXT_PUBLIC_API_URL: "http://localhost:5000"
    networks:
      - tunihire_network
  tunihire_admin_panel:
    image: node:18-alpine
    container_name: tunihire_admin_panel_app
    restart: unless-stopped
    ports:
      - "3002:3002"
    depends_on:
      - tunihire_backend
    volumes:
      - ./Admin-Panel:/app
    working_dir: /app
    command: sh -c "npm install && npm run start"    
    environment:
      NODE_ENV: development
      PORT: 3002
      REACT_APP_API_URL: "http://localhost:5000"
    networks:
      - tunihire_network

  tunihire_ai_service:
    image: ${NEXUS_REGISTRY_URL}/tunihire-ai-service:${BASE_APP_VERSION}
    build:
      context: ./AI-Service
      dockerfile: Dockerfile.new
      args:
        - BUILDKIT_NETWORK_MODE=host
    container_name: tunihire_ai_service_app
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      PYTHONUNBUFFERED: 1
      JWT_SECRET_KEY: ${JWT_SECRET}
      # Add other AI service specific env vars here if needed (non-secret)
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - tunihire_network

volumes:
  mongo_data:
    driver: local

networks:
  tunihire_network:
    driver: bridge
